#!/usr/bin/env python3
"""
Regenerates src/data/openmojiIcons.ts from the installed `openmoji`
package's "black" (outline) variant -- actual emoji redrawn as clean
line art specifically for print/coloring use, which is the most
"playful" of the four bundled libraries.

    npm install -D openmoji@latest
    npx --yes svgo -f node_modules/openmoji/black/svg -r --precision 1 \\
      -o /tmp/openmoji-optimized
    python3 scripts/gen-icons-openmoji.py

Run through SVGO first (precision 1 -- OpenMoji's 72-unit viewBox is
already fairly coarse, so precision 0 felt like it was cutting it close
on some curved faces): cuts the filtered subset from ~3.6MB to ~1.5MB
with no visible quality loss at label print sizes.

Filters applied to data/openmoji.json's ~4500 entries:
  - drop skin-tone-modified duplicates (skintone field set) -- in
    black-only line art a skin-tone variant renders identically to its
    base emoji, so keeping both is pure clutter, not a real choice.
  - drop the "flags" and "component" groups -- flags carry no meaningful
    line art once color is removed, and "component" entries are
    body-part fragments used to compose other emoji, not standalone icons.
That leaves ~2200 entries.

Unlike Lucide/Phosphor, OpenMoji icons mix per-element styling in the
source itself (most paths explicitly set fill="none" stroke="#000000"
for outlines; a few small detail shapes -- e.g. eye dots -- carry no
fill/stroke at all, relying on SVG's own default fill=black). Both
render correctly under this project's "fill mode" (see
editor/iconLibraries.ts): the renderer's wrapper defaults to
fill="#000000" stroke="none", which the self-styled outline elements
override, and the undecorated detail shapes correctly fall back to.

License: CC BY-SA 4.0 -- requires attribution AND share-alike. See the
credit line in hub/HubPage.tsx.
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG_DIR = os.path.join(ROOT, "node_modules", "openmoji")
SVG_DIR = "/tmp/openmoji-optimized"
OUT_PATH = os.path.join(ROOT, "src", "data", "openmojiIcons.ts")

EXCLUDED_GROUPS = {"flags", "component"}


def main() -> None:
    with open(os.path.join(PKG_DIR, "data", "openmoji.json")) as f:
        metadata = json.load(f)

    entries = []
    for item in metadata:
        if item.get("skintone"):
            continue
        if item.get("group") in EXCLUDED_GROUPS:
            continue
        hexcode = item["hexcode"]
        path = os.path.join(SVG_DIR, f"{hexcode}.svg")
        if not os.path.exists(path):
            continue
        with open(path) as f:
            raw = f.read()
        m = re.search(r"<svg[^>]*>(.*)</svg>", raw, flags=re.S)
        inner = m.group(1) if m else ""
        inner = re.sub(r'\sid="[^"]*"', "", inner)
        inner = re.sub(r"\s+", " ", inner).strip()
        if not inner:
            continue

        name = item["annotation"]
        tags = [t.strip() for t in item.get("tags", "").split(",") if t.strip()]
        entries.append((name, tags, inner))

    header = '''/**
 * OpenMoji "black" (outline) icons (https://openmoji.org), CC BY-SA 4.0
 * -- actual emoji redrawn as clean line art for print/coloring use, the
 * most "playful" of the four bundled libraries. See this script's
 * docstring for the filtering applied (skin-tone dedup, flags/component
 * groups dropped) and for why these render correctly under this
 * project's "fill mode" despite mixing per-element stroke/fill styling.
 *
 * License requires attribution AND share-alike -- see hub/HubPage.tsx's
 * credit line.
 *
 * Native viewBox is 0 0 72 72 (see editor/iconLibraries.ts). EDITOR-ONLY,
 * lazy-loaded within the editor -- see phosphorIcons.ts's doc for why.
 *
 * Generated by scripts/gen-icons-openmoji.py -- do not hand-edit.
 */
import type { IconEntry } from './iconTypes'

export const OPENMOJI_ICONS: readonly IconEntry[] = [
'''
    lines = ["  " + json.dumps([name, tags, svg]) + "," for name, tags, svg in entries]
    footer = "]\n"

    with open(OUT_PATH, "w") as f:
        f.write(header + "\n".join(lines) + "\n" + footer)

    print(f"wrote {len(entries)} icons to {OUT_PATH}")


if __name__ == "__main__":
    main()
