#!/usr/bin/env python3
"""
Regenerates src/data/lucideIcons.ts from the installed lucide-static
package. Run after bumping the lucide-static devDependency version:

    npm install -D lucide-static@latest
    python3 scripts/gen-icons.py

Reads node_modules/lucide-static/tags.json for the canonical (non-alias)
icon list and per-icon search tags, and node_modules/lucide-static/icons/
for each icon's raw SVG. Extracts just the inner markup (paths/circles/
etc, no outer <svg> wrapper, no stroke/fill/color attributes) so the
render-side Icon component can apply its own color and stroke width.
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUCIDE_DIR = os.path.join(ROOT, "node_modules", "lucide-static")
OUT_PATH = os.path.join(ROOT, "src", "data", "lucideIcons.ts")


def main() -> None:
    with open(os.path.join(LUCIDE_DIR, "tags.json")) as f:
        tags_map = json.load(f)

    icons_dir = os.path.join(LUCIDE_DIR, "icons")
    entries = []
    for name in sorted(tags_map.keys()):
        path = os.path.join(icons_dir, name + ".svg")
        if not os.path.exists(path):
            continue
        with open(path) as f:
            raw = f.read()
        raw = re.sub(r"<!--.*?-->", "", raw, flags=re.S)
        m = re.search(r"<svg[^>]*>(.*)</svg>", raw, flags=re.S)
        inner = m.group(1) if m else ""
        inner = re.sub(r"\s+", " ", inner).strip()
        entries.append((name, tags_map[name], inner))

    header = '''/**
 * Lucide icons (https://lucide.dev), MIT/ISC-licensed line-art icon set --
 * chosen for thermal printing because its consistent 2px-stroke outline
 * style (24x24 viewBox, round caps/joins) is exactly the kind of clean
 * line art that survives 1-bit thresholding, unlike filled/detailed
 * icon styles. Each entry is [name, search tags, inner SVG markup] --
 * markup only (no outer <svg> wrapper, no stroke/fill/color attributes),
 * so the icon block renderer applies its own color/stroke-width.
 *
 * EDITOR-ONLY: this is a large (~550KB) data file used by the icon
 * picker's search grid. render/nodes/Icon.tsx never imports it -- a
 * chosen icon's markup is resolved once and baked directly into the doc
 * (see codec/types.ts IconBlock), so the viewer bundle is entirely
 * unaffected by this file's size.
 *
 * Generated by scripts/gen-icons.py from lucide-static -- do not hand-edit.
 */
import type { IconEntry } from './iconTypes'

export const LUCIDE_ICONS: readonly IconEntry[] = [
'''
    lines = ["  " + json.dumps([name, tags, svg]) + "," for name, tags, svg in entries]
    footer = "]\n"

    with open(OUT_PATH, "w") as f:
        f.write(header + "\n".join(lines) + "\n" + footer)

    print(f"wrote {len(entries)} icons to {OUT_PATH}")


if __name__ == "__main__":
    main()
