#!/usr/bin/env python3
"""
Regenerates src/data/gameIcons.ts from a local checkout of the
game-icons/icons GitHub repo (not published as a clean npm package --
the closest thing, `game-icons-react`, ships precompiled React components
rather than raw SVG, which is more fragile to parse than the source
repo's actual .svg files), run through SVGO first: these are hand-
illustrated paths (not simple line icons), and at full precision the raw
set is ~6.7MB -- integer-precision optimization gets that down to
~2.3MB with no visible quality loss at the tiny sizes these render at on
a label (a coordinate on a 512-unit canvas rounds to well under a dot's
width once scaled to a 40-80 dot icon).

    curl -sL -o /tmp/game-icons.tar.gz \\
      https://codeload.github.com/game-icons/icons/tar.gz/refs/heads/master
    mkdir -p /tmp/game-icons-extracted && tar -xzf /tmp/game-icons.tar.gz -C /tmp/game-icons-extracted
    npx --yes svgo -f /tmp/game-icons-extracted/icons-master -r --precision 0 \\
      -o /tmp/game-icons-optimized
    python3 scripts/gen-icons-game.py

License: CC BY 3.0 (https://creativecommons.org/licenses/by/3.0/) --
game-icons.net asks that a credit line be shown somewhere ("Icons made by
{author}. Available on https://game-icons.net"); given this bundles
~4000 icons from ~35 authors, this project shows one blanket credit
(see hub/HubPage.tsx) rather than per-icon inline attribution, which
game-icons.net's own FAQ treats as acceptable for bulk use.

Each source SVG is a 512x512 canvas with TWO layers: a full-canvas
background path (implicitly black, no fill attribute) and one or more
foreground paths with fill="#fff" (white) -- see the game-icons/icons
README: "all icons have a white foreground on a black background" by
default. We want the opposite (black icon, transparent background) for
printing on white label stock, so this script keeps ONLY the fill="#fff"
paths and drops their fill attribute entirely, letting the renderer's own
default black fill apply (see editor/iconLibraries.ts's fillMode).
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXTRACTED_DIR = "/tmp/game-icons-optimized"
OUT_PATH = os.path.join(ROOT, "src", "data", "gameIcons.ts")

WHITE_FILL_RE = re.compile(r'fill="\s*(#fff+|white)\s*"', re.IGNORECASE)


def extract_paths(raw: str) -> list[str]:
    paths = re.findall(r"<path\b[^>]*/>", raw, flags=re.S)
    white_paths = [p for p in paths if WHITE_FILL_RE.search(p)]
    kept = white_paths if white_paths else paths
    cleaned = []
    for p in kept:
        p = re.sub(r'\sfill="[^"]*"', "", p)
        cleaned.append(p)
    return cleaned


def main() -> None:
    if not os.path.isdir(EXTRACTED_DIR):
        raise SystemExit(f"expected a game-icons/icons checkout at {EXTRACTED_DIR} -- see this script's docstring")

    entries = []
    authors = set()
    for author in sorted(os.listdir(EXTRACTED_DIR)):
        author_dir = os.path.join(EXTRACTED_DIR, author)
        if not os.path.isdir(author_dir):
            continue
        svg_files = sorted(f for f in os.listdir(author_dir) if f.endswith(".svg"))
        if not svg_files:
            continue
        authors.add(author)
        for filename in svg_files:
            name = filename[:-4]
            with open(os.path.join(author_dir, filename)) as f:
                raw = f.read()
            paths = extract_paths(raw)
            if not paths:
                continue
            svg = " ".join(paths)
            tags = name.replace("_", "-").split("-") + [author]
            entries.append((name, tags, svg))

    header = f'''/**
 * Game-icons.net icons (https://game-icons.net), CC BY 3.0 -- a
 * fantasy/game-themed silhouette set (swords, potions, dragons) for a
 * genuinely different, fun personality than Lucide/Phosphor's UI-style
 * icons. Solid black shapes print very reliably in 1-bit.
 *
 * License requires attribution -- see hub/HubPage.tsx's credit line
 * (~{len(authors)} contributing authors, blanket-credited rather than
 * per-icon, per game-icons.net's own guidance for bulk use).
 *
 * Native viewBox is 0 0 512 512 (see editor/iconLibraries.ts). Source
 * SVGs ship a black background + white foreground; this data keeps only
 * the foreground path(s), fill attribute stripped, so the renderer's own
 * black fill applies over a transparent background instead.
 *
 * EDITOR-ONLY, lazy-loaded within the editor -- see phosphorIcons.ts's
 * doc for why. Generated by scripts/gen-icons-game.py -- do not hand-edit.
 */
import type {{ IconEntry }} from './iconTypes'

export const GAME_ICONS: readonly IconEntry[] = [
'''
    lines = ["  " + json.dumps([name, tags, svg]) + "," for name, tags, svg in entries]
    footer = "]\n"

    with open(OUT_PATH, "w") as f:
        f.write(header + "\n".join(lines) + "\n" + footer)

    print(f"wrote {len(entries)} icons from {len(authors)} authors to {OUT_PATH}")


if __name__ == "__main__":
    main()
