#!/usr/bin/env python3
"""
Regenerates src/data/phosphorIcons.ts from the installed
@phosphor-icons/core package's "fill" weight (solid black shapes -- a
friendlier, chunkier look than Lucide's thin strokes, and solid fills
print more reliably than fine lines on thermal paper besides).

    npm install -D @phosphor-icons/core@latest
    python3 scripts/gen-icons-phosphor.py

Icon metadata (name/tags/categories) comes from the package's own
dist/index.mjs, which exports an `icons` array -- read via a small Node
ESM import rather than regex, since it's a real JS module.
"""

import json
import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG_DIR = os.path.join(ROOT, "node_modules", "@phosphor-icons", "core")
OUT_PATH = os.path.join(ROOT, "src", "data", "phosphorIcons.ts")


def load_metadata():
    node_script = (
        "import('@phosphor-icons/core').then(m => "
        "process.stdout.write(JSON.stringify(m.icons.map(i => "
        "({name: i.name, tags: [...i.categories, ...i.tags]})))))"
    )
    result = subprocess.run(["node", "-e", node_script], cwd=ROOT, capture_output=True, text=True, check=True)
    return json.loads(result.stdout)


def main() -> None:
    metadata = load_metadata()
    entries = []
    for item in metadata:
        name = item["name"]
        path = os.path.join(PKG_DIR, "assets", "fill", f"{name}-fill.svg")
        if not os.path.exists(path):
            continue
        with open(path) as f:
            raw = f.read()
        m = re.search(r"<svg[^>]*>(.*)</svg>", raw, flags=re.S)
        inner = m.group(1) if m else ""
        inner = re.sub(r"\s+", " ", inner).strip()
        # Dedupe tags (categories + tags can overlap) and drop the "*new*"
        # marker some entries carry -- it's a website UI badge, not a
        # search term.
        tags = [t for i, t in enumerate(item["tags"]) if t != "*new*" and t not in item["tags"][:i]]
        entries.append((name, tags, inner))

    header = '''/**
 * Phosphor icons (https://phosphoricons.com), MIT-licensed -- the "fill"
 * weight specifically: solid black shapes rather than outlines, for a
 * friendlier/chunkier look than Lucide and because solid fills survive
 * 1-bit thresholding even more reliably than thin strokes. Native
 * viewBox is 0 0 256 256 (see editor/iconLibraries.ts) -- NOT 24x24 like
 * Lucide, so IconBlock carries its own viewBox per instance.
 *
 * EDITOR-ONLY, and lazy-loaded even within the editor (see
 * iconLibraries.ts's dynamic import) -- this and the other bundled
 * libraries add up to several MB combined, so nothing loads until its
 * tab is opened in the icon picker. render/nodes/Icon.tsx never imports
 * this file; a chosen icon's markup is resolved once and baked directly
 * into the doc.
 *
 * Generated by scripts/gen-icons-phosphor.py -- do not hand-edit.
 */
import type { IconEntry } from './iconTypes'

export const PHOSPHOR_ICONS: readonly IconEntry[] = [
'''
    lines = ["  " + json.dumps([name, tags, svg]) + "," for name, tags, svg in entries]
    footer = "]\n"

    with open(OUT_PATH, "w") as f:
        f.write(header + "\n".join(lines) + "\n" + footer)

    print(f"wrote {len(entries)} icons to {OUT_PATH}")


if __name__ == "__main__":
    main()
